# name: io.BlockingIOError 
exception io.BlockingIOError