# name: _thread.error 
exception _thread.error