# name: c.PyErr_SetFromErrno 
PyObject* PyErr_SetFromErrno(PyObjectÂ *type)