# name: c.PyErr_ExceptionMat 
int PyErr_ExceptionMatches(PyObjectÂ *exc)